### ISSUE TITLE
Change primary color

### ISSUE THREAD

**Issue by mitch2k** [creativetimofficial/ct-material-dashboard-pro-laravel#12]
Hi,

I'm trying to change the primary color for Laravel Material dasbhoard pro according to https://demos.creative-tim.com/material-dashboard-pro/docs/2.1/getting-started/build-tools.html#change-brand-colors
I have changed the colors in public/material/scss/material-dashboard/variables

Now I'm trying to run gulp compile-scss, but I get 

`C:\wamp64\www\ciportal>gulp compile-scss[11:06:00] No gulpfile found`

There is indeed no gulp file. Also in the downloaded file, I can't see the gulp file.
How should I proceed to change the primay color?

Thanks

**Comment by teamupdivision** [comment]
Hello, thank you for using our products!

For building the Laravel page we have not used scss.
In order to change the primary color, you need to replace it directly everywhere in the css/material-dashboard.css.

Thank you

**Comment by aefika** [comment]
I've managed to generate the css from the included material-dashboard.scss using Laravel Mix & Webpack. Here are my steps:
1. Moved \public\material\scss\ to \resources\scss\
2. Edited webpack.mix.js with a single instruction: mix.sass('resources/scss/material-dashboard.scss', 'public/css')
3. npm install (only once)
4. set OPENSSL_CONF= // Fixes open SSL problem
5. npm run dev
At this point the included css file seems to be exactly to the generated css (there are more lines on the generated css though)
You can always change the destination folder in the mix instruction
@teamupdivision, it might be a good option to update the documentation to build the css. Laravel uses Laravel Mix

**Comment by teamupdivision** [comment]
Hello @aefika, thanks for the answer and for using our products!

Can you please help us out with where you found the different position values, can you send us the exact css file and css line where the property is?

Thanks

**Comment by aefika** [comment]
A diff shows what are the differences to the file attached. 

 

When looking into those differences, the vast majority are spaces or quotes, but some of them look more than that. I was under the impression that the scss files where the ones used to generate the css.

 

I’m using the Laravel Mix compiled css because I’m changing colors globally.

 

Some of the differences that I see could affect behaviour are:

 

.register-page .bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {

-  width:calc(100% - 56px) !important;

-}

-

-.page-header > .container {

-  flex-grow: 1;

-}

-

-.page-header {

-  flex-direction: column;

-  padding-bottom: 0 !important;

-}

-

-.page-header .footer {

-  flex-grow: 0;

-  position: static

-}

-

-.page-header.login-page {

-  max-height: inherit;

-  height:auto;

-}

-

-.off-canvas-sidebar .navbar-collapse:after {

-  background-color: #282828;

-}

-

-.off-canvas-sidebar .wrapper-full-page .page-header {

-  padding-bottom: 0px !important;

-}

-

-/*# sourceMappingURL=dashboard-pro.css.map */

 

 

Luis Nicho, Ing., MGP, PMP

Directeur des opérations

AEfika Services-conseil

 

T +1 (514) 258 6215

C  <mailto:luis.nicho@aefika.com> luis.nicho@aefika.com

 

 



OUTILS PRATIQUES SUR MESURE POUR

RÉVOLUTIONNER VOTRE TRAVAIL

 <http://www.aefika.com/> www.aefika.com

 

(SVP noter que je suis basé à Montréal et que mon fuseau horaire est UTC -05 :00)

**Comment by teamupdivision** [comment]
Hello @aefika 
The different static values for the footer are based on the page it's shown. In a page with a fixed height (full-sized) like this one: https://www.creative-tim.com/live/material-dashboard-pro-laravel has a position: static; to always stay on the bottom of the page.
